
- name: Git clone rbenv
  git:
    repo: 'https://github.com/sstephenson/rbenv.git'
    dest: '~/.rbenv'
  become: no
  register: clone_rbenv

- name: Git clone ruby-build
  git:
    repo: 'https://github.com/sstephenson/ruby-build.git'
    dest: '~/.rbenv/plugins/ruby-build'
  become: no
  when: clone_rbenv.changed

- name: Set rbenv1
  lineinfile: >
    dest=~/.zshrc
    line='eval "$(rbenv init -)"'
  # when: clone_rbenv.changed
  become: no

- name: Set rbenv2
  lineinfile: >
    dest=~/.zshrc
    line='export PATH="$HOME/.rbenv/bin:$PATH"'
  when: clone_rbenv.changed
  become: no

- name: Install ruby's
  shell: "RUBY_CONFIGURE_OPTS=--disable-install-doc ~/.rbenv/bin/rbenv install {{ version }}"
  become: no
  tags: [packages]
  with_items:
  - "{{ rails.rbenv.versions }}"
  loop_control:
    loop_var: version
  when: clone_rbenv.changed

- name: "Set global ruby {{ rails.rbenv.versions[0] }}"
  shell: "~/.rbenv/bin/rbenv global {{ rails.rbenv.versions[0] }}; ~/.rbenv/bin/rbenv rehash"
  become: no
  tags: [packages]
